wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 10
architecture:
  desc: null
  value: resnet18
dataset:
  desc: null
  value: original
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717584816
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.12.3
      5: 0.17.0
      6: 4.40.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
